# Generated by Django 4.1.7 on 2023-08-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concert", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="concertattending",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
